name: validating pull request code
'on': pull_request
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Only run linting if the script exists
      - name: Check if lint script exists
        id: lint_check
        run: |
          if grep -q '"lint"' package.json; then
            echo "lint_exists=true" >> $GITHUB_OUTPUT
          else
            echo "lint_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Lint code (fail on errors but not warnings)
        if: steps.lint_check.outputs.lint_exists == 'true'
        run: npm run lint -- --quiet --max-warnings=9999

      - name: Build project
        run: npm run build

      # Check for vulnerabilities but don't fail the build
      - name: Check for vulnerabilities
        run: npm audit --production || echo "Vulnerability check completed with issues"
